FROM python:3.11-slim

WORKDIR /app

# Copy only requirements first to leverage Docker's caching mechanism
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .


CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]