version: '3.8'

services:
  django:
    image: vsaluja/job-tracker-backend:latest
    container_name: django_container
    restart: always
    # Only allow requests from inside EC2
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      # These must match the NAME, USER, and PASSWORD in your Django settings.py
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: