# Generated by Django 6.0.6 on 2026-06-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('job_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
